export const styles = {
    body: {
      display: 'flex',
      justifyContent: 'center',
      height: '100%',
      backgroundColor:"#F5B301"
    },
    fitAppLogo: {
      width: 120,
      height: 60,
      marginLeft: 10,
      marginTop: -30,
      marginBottom: 10,
    },
    insidePanel: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: 30,
        marginRight: 30,
        height: "80%",
        backgroundColor: "#2A2E34",
        borderRadius: 20,
    },
    headerText:{
      paddingTop: 20,
      paddingBottom: 20,
      fontSize: 40,
      fontWeight: 'bold',
      textAlign: 'center',
      color: "white",
    },
    infoText:{
      fontSize: 25,
      textAlign: 'center',
      color: "white",
      lineHeight: 30,
      textAlign: 'center',
      width: 200
      //marginLeft:10,
    },
    importPhoto:{
        marginLeft: 'auto',
        marginRight: 'auto',
        width: 120,
        height: 120,
        backgroundColor:"#3B3F46",
        borderRadius: 60,
        marginBottom: 20,
    },
    importPhotoContainer:{
      marginLeft: 'auto',
      marginRight: 'auto',
      width: 120,
      height: 120,
      backgroundColor:"#3B3F46",
      borderRadius: 60,
      marginBottom: 20,
  },
    changePasswordButton: {
      // marginTop: 1,
      marginLeft: 'auto',
      marginRight: 'auto',
      width: 200,
      borderRadius: 7,
      backgroundColor: "white",
      textColor: "red",
    },
    buttonText: {
      fontSize:18,
      color: "black"
    },
    logoImg: {
      width: 30,
      height: 30,
      marginBottom: 60,

    },
    rowContainer: {
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'space-between',
      width: 170,
    },
    rowContainerPassword: {
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'center',
      width: 180,
      marginTop: 20,
    },
    loginInput: {
      backgroundColor: '#FFF',
    },
    modalView:{
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: 30,
        marginRight: 30,
        marginTop: 100,
        height: "76%",
        backgroundColor: "#2A2E34",
        borderRadius: 20,
    },
    headerPassword:{
      fontSize: 30,
      lineHeight: 30,
      color: 'white',
    },
    textButtonCamera:{
      color: 'black',
      fontSize: 18,
    },
    takePhotoButton: {
      marginLeft: 'auto',
      marginRight: 'auto',
      marginTop: 10,
      width: "50%",
      borderRadius: 7,
      backgroundColor: 'white',
    },
    rotateCamera:{
      marginLeft: 'auto',
      marginRight: 'auto',
      marginTop: 90,
      width: "50%",
      borderRadius: 7,
      backgroundColor: 'white',
    },
    newImage:{
      width: 120,
      height: 120,
      borderRadius: 60,
      backgroundColor:"#3B3F46",
    },
    spinner:{
      position: 'absolute',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      width:'100%',
      height:'100%',
      backgroundColor:"black",
      opacity: 0.6,
      zIndex: 1,
    }


  }